package au.com.noojee.universe;

/*
 * Elements.java
 *
 * Created on 20 January 2002, 21:41
 */

/**
 *
 * @author  bsutton
 */
public class Elements extends javax.swing.JPanel
{
	private static final long serialVersionUID = 1L;
	
	private final int m_nAtomNode = 0;
	private final int m_nMoleculeNode = 1;
	private final String[] m_astrRoot = new String[]  {"Atoms", "Molecules"};
	
	/** Creates new form Elements */
	public Elements()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		jScrollPane1 = new javax.swing.JScrollPane();
		m_treeElements = new javax.swing.JTree(m_astrRoot);
		
		setLayout(new java.awt.BorderLayout());
		
		jScrollPane1.setViewportView(m_treeElements);
		
		add(jScrollPane1, java.awt.BorderLayout.CENTER);
		
	}//GEN-END:initComponents
	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTree m_treeElements;
	// End of variables declaration//GEN-END:variables
	
}
