package au.com.noojee.universe;

import java.awt.BorderLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;


/*
 * Filter.java
 *
 * Created on 20 January 2002, 21:12
 */

/**
 * 
 * @author bsutton
 */
public class Filter extends javax.swing.JDialog
{
	private static final long serialVersionUID = 1L;

	/** Creates new form Filter */
	public Filter(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
	}

//	private void onDragDrop(Object source, DragSourceEvent e)
//	{
//
//		// If text is in the object, write it into the edit control.
//		if (e.data.getDataPresent(ElementNode.class))
//		{
//			ElementNode node = (ElementNode) e.data.getData(ElementNode.class);
//			m_edParticle.setText(node.getName());
//		}
//
//	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents()// GEN-BEGIN:initComponents
	{
		m_btnGroupShow = new javax.swing.ButtonGroup();
		m_bntGroupFilter = new javax.swing.ButtonGroup();
		m_rdoShow = new javax.swing.JRadioButton();
		jLabel1 = new javax.swing.JLabel();
		m_edParticle = new javax.swing.JTextField();
		m_rdoHIde = new javax.swing.JRadioButton();
		m_btnReset = new javax.swing.JButton();
		m_btnOK = new javax.swing.JButton();
		m_btnApply = new javax.swing.JButton();
		m_btnCancel = new javax.swing.JButton();
		m_btnApplyToExisting = new javax.swing.JRadioButton();
		m_btnNewFilter = new javax.swing.JRadioButton();

		//getContentPane().setLayout(null);

		setTitle("Filter");
		setName("m_dlgFilter");
		setResizable(true);
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				closeDialog(evt);
			}
		});

		m_rdoShow.setText("Show");
		m_btnGroupShow.add(m_rdoShow);
		getContentPane().add(m_rdoShow);
		m_rdoShow.setBounds(23, 55, 57, 25);

		jLabel1.setText("Particle:");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(4, 15, 64, 22);

		getContentPane().add(m_edParticle);
		m_edParticle.setBounds(60, 18, 180, 19);

		m_rdoHIde.setText("Hide");
		m_btnGroupShow.add(m_rdoHIde);
		getContentPane().add(m_rdoHIde);
		m_rdoHIde.setBounds(94, 57, 50, 25);

		m_btnReset.setText("Reset");
		m_btnReset.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				onReset(evt);
			}
		});

		getContentPane().add(m_btnReset);
		m_btnReset.setBounds(172, 49, 67, 27);

		m_btnOK.setText("OK");
		m_btnOK.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				onOK(evt);
			}
		});

		getContentPane().add(m_btnOK);
		m_btnOK.setBounds(30, 149, 51, 27);

		m_btnApply.setText("Apply");
		m_btnApply.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				onApply(evt);
			}
		});

		getContentPane().add(m_btnApply);
		m_btnApply.setBounds(90, 148, 65, 27);

		m_btnCancel.setText("Cancel");
		m_btnCancel.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				onCancel(evt);
			}
		});

		getContentPane().add(m_btnCancel);
		m_btnCancel.setBounds(161, 147, 73, 27);

		m_btnApplyToExisting.setText("Apply to existing filter");
		m_bntGroupFilter.add(m_btnApplyToExisting);
		getContentPane().add(m_btnApplyToExisting);
		m_btnApplyToExisting.setBounds(32, 89, 147, 25);

		m_btnNewFilter.setText("New filter");
		m_bntGroupFilter.add(m_btnNewFilter);
		getContentPane().add(m_btnNewFilter);
		m_btnNewFilter.setBounds(36, 122, 79, 25);

		this.setBounds(0,0,250,250);
		pack();
	}// GEN-END:initComponents

	private void onReset(java.awt.event.ActionEvent evt)// GEN-FIRST:event_onReset
	{// GEN-HEADEREND:event_onReset
		// Add your handling code here:
	}// GEN-LAST:event_onReset

	private void onCancel(java.awt.event.ActionEvent evt)// GEN-FIRST:event_onCancel
	{// GEN-HEADEREND:event_onCancel
		// Add your handling code here:
	}// GEN-LAST:event_onCancel

	private void onApply(java.awt.event.ActionEvent evt)// GEN-FIRST:event_onApply
	{// GEN-HEADEREND:event_onApply
		// Add your handling code here:
	}// GEN-LAST:event_onApply

	private void onOK(java.awt.event.ActionEvent evt)// GEN-FIRST:event_onOK
	{// GEN-HEADEREND:event_onOK
		// Add your handling code here:
	}// GEN-LAST:event_onOK

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt)
	{// GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
	}// GEN-LAST:event_closeDialog

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{
		JFrame frame = new javax.swing.JFrame();
		frame.setSize(250,250);
		
		
		//2. Optional: What happens when the frame closes?
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		//3. Create components and put them in the frame.
		//...create emptyLabel...
		frame.getContentPane().add(new JLabel("Universe Viewer"), BorderLayout.CENTER);
		

		//4. Size the frame.
		frame.pack();

		new Filter(frame, false).setVisible(true);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup m_btnGroupShow;
	private javax.swing.ButtonGroup m_bntGroupFilter;
	private javax.swing.JRadioButton m_rdoShow;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField m_edParticle;
	private javax.swing.JRadioButton m_rdoHIde;
	private javax.swing.JButton m_btnReset;
	private javax.swing.JButton m_btnOK;
	private javax.swing.JButton m_btnApply;
	private javax.swing.JButton m_btnCancel;
	private javax.swing.JRadioButton m_btnApplyToExisting;
	private javax.swing.JRadioButton m_btnNewFilter;
	// End of variables declaration//GEN-END:variables

}
