package au.com.noojee.universe;

import java.awt.BorderLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * Viewer.java
 *
 * Created on 20 January 2002, 20:52
 */

/**
 * 
 * @author bsutton
 */
public class Viewer extends javax.swing.JFrame
{
	private static final long serialVersionUID = 1L;
	
	/** Creates new form Viewer */
	public Viewer()
	{
		super("Universe Viewer");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents()// GEN-BEGIN:initComponents
	{
		jPopupMenu1 = new javax.swing.JPopupMenu();
		jMenuItem1 = new javax.swing.JMenuItem();

		jMenuItem1.setText("Item");
		jPopupMenu1.add(jMenuItem1);

		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				exitForm(evt);
			}
		});


		//2. Optional: What happens when the frame closes?
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		//3. Create components and put them in the frame.
		//...create emptyLabel...
		this.getContentPane().add(new JLabel("Universe Viewer"), BorderLayout.CENTER);
		this.getContentPane().add(jPopupMenu1);
		

		//4. Size the frame.
		this.pack();

	}// GEN-END:initComponents

	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt)
	{// GEN-FIRST:event_exitForm
		System.exit(0);
	}// GEN-LAST:event_exitForm


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPopupMenu jPopupMenu1;
	private javax.swing.JMenuItem jMenuItem1;
	// End of variables declaration//GEN-END:variables

}
